# python-ci.yml
name: basic CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-run-pytest:

    runs-on: ubuntu-latest

    steps:
    # First step (unnamed here) is to checkout to the branch that triggered
    # the event
    - uses: actions/checkout@v3

    # Second step: install python 3.10
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"


    # Third step: install python packages using a requirements file
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip cython wheel
        pip install -r requirements_ci.txt

    # Fourth step: run tests with Pytest
    - name: Build test Docker image
      run: docker build -f tests/Dockerfile.test -t api-test .

    - name: Run test Docker container
      run: docker run -d -e PORT=8000 -p 8000:8000 --name api-test-container -p 8080:8000 api-test

    - name: Run tests
      run: make pytest

    - name: Stop test Docker container
      run: docker stop api-test-container && docker rm api-test-container
